# Usar Usuario, Clave y Base de Datos con su propia información, por ejemplo:
# POSTGRES_USER: gonzalesj     --->>> su apellido más la primera letra de su nombre
# POSTGRES_PASSWORD: Jesus556  --->>> una clave que ud. elija
# POSTGRES_DB: Prueba            --->>> la Base de Datos deberá tener el nombre de Prueba 

version: '1.1'

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Jesus55
      MYSQL_USER: Arielc
      MYSQL_PASSWORD: Jesus55
      MYSQL_DATABASE: Prueba

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8081:80
